import { NAME } from "./constants";

export const TOGGLE_CONTEXT_MENU = NAME + "/TOGGLE_CONTEXT_MENU";
export const CLOSE_CONTEXT_MENU = NAME + "/CLOSE_CONTEXT_MENU";
export const OPEN_CONTEXT_MENU = NAME + "/OPEN_CONTEXT_MENU";
export const SELECTED_STRING = NAME + "/SELECTED_STRING";
export const SELECTED_PARENT = NAME + "/SELECTED_PARENT";
export const SELECTION_POSITION = NAME + "/SELECITON_POSITION";
