import { NAME } from "./constants";

export const ARCHIVE_CURRENT_DATA = NAME + "/ARCHIVE_CURRENT_DATA";
export const LOAD_DOCUMENT_DATA_SETS = NAME + "/LOAD_DOCUMENT_DATA_SETS";
export const DELETE_DOCUMENT_DATA_SET = NAME + "/DELETE_DOCUMENT_DATA_SET";
export const DOCUMENT_CHANGE = NAME + "/DOCUMENT_CHANGE";
